
image_size = [512, 512]
output_data_root = 'output/'

[data_module_config]
data_root = 'testdata/'
test_batch_size = 1
preload = false
debug = false

[tester_config]
model = 'hrnet48'
pretrain_load_dir = 'output/ML_Tibial_nccloss_3_15'
pretrain_load_prefix = '500'